GET http://localhost:3003/api/blogs/

###
PUT http://localhost:3003/api/blogs/5a422a851b54a676234d17f7/comment
Content-Type: application/json

{
    "comment":"this is a comment"
}

###
DELETE http://localhost:3003/api/blogs/5f1900582c3c8dc85be55d6c

###
GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json

{
    "title":"new blog created by usera 3",
    "author":"User A",
    "userId":"5f1f0272784cc319c44849d9",
    "url":"usera.com"
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json

{
    "title":"new blog created by usera 4",
    "author":"User A",
    "url":"usera.com"
}

### 
DELETE http://localhost:3003/api/blogs/5f1900582c3c8dc85be55d6c