GET http://localhost:3003/api/blogs/

### 
GET http://localhost:3003/api/users/

### 
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "usera",
    "name":"UserA",
    "password":"pwd"
}

### 
POST http://localhost:3003/api/login/
Content-Type: application/json

{
    "username": "hellas",
    "password":"pwd"
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNWYxZjAzMzdhZTY1YWUyMjFmNWU2YzY4IiwiaWF0IjoxNTk1OTUyODYwfQ.o8ITX-j4q8TWcPyJMuLqsH8srnjioTxObs6UPqHxy90

{
    "title":"new blog created by hellas with username and token middleware",
    "url":"blog.com"
}

###
DELETE  http://localhost:3003/api/blogs/5f204f25a264fe57997af073
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNWYxZjAzMzdhZTY1YWUyMjFmNWU2YzY4IiwiaWF0IjoxNTk1OTUyODYwfQ.o8ITX-j4q8TWcPyJMuLqsH8srnjioTxObs6UPqHxy90


### 
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "hellas",
    "name":"Arto Hellas",
    "password":"pwd"
}

### test error user creation
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "he",
    "name":"Arto Hellas",
    "password":"pwd"
}

### test error user creation
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "heee",
    "name":"Arto Hellas",
    "password":"p"
}

